// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5yoH53sEPJ_tIhI7OlBeiblWypg0pz80',
    appId: '1:597414816582:web:1211e91fbbb099ffde1347',
    messagingSenderId: '597414816582',
    projectId: 'harmony-music-player-a56bd',
    authDomain: 'harmony-music-player-a56bd.firebaseapp.com',
    storageBucket: 'harmony-music-player-a56bd.appspot.com',
    measurementId: 'G-GMB853Q55C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTiKW_WfyQs0Drbf2N21SickmldrIa5L8',
    appId: '1:597414816582:android:3faeff03649a6640de1347',
    messagingSenderId: '597414816582',
    projectId: 'harmony-music-player-a56bd',
    storageBucket: 'harmony-music-player-a56bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAger50Nm2M2Vw5Cfn9G-TA4i2xTaiOWOI',
    appId: '1:597414816582:ios:4b1baeb73c8a3fb5de1347',
    messagingSenderId: '597414816582',
    projectId: 'harmony-music-player-a56bd',
    storageBucket: 'harmony-music-player-a56bd.appspot.com',
    iosBundleId: 'com.example.musicplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAger50Nm2M2Vw5Cfn9G-TA4i2xTaiOWOI',
    appId: '1:597414816582:ios:002f5d37ec89bc25de1347',
    messagingSenderId: '597414816582',
    projectId: 'harmony-music-player-a56bd',
    storageBucket: 'harmony-music-player-a56bd.appspot.com',
    iosBundleId: 'com.example.musicplayer.RunnerTests',
  );
}
